config/routes.rb
Rails.application.routes.draw do

  post 'invitations/send_invitation_email'

  get 'home/welcome'

  match ':controller(/:action(/:id))', :via => [:get, :post, :patch, :delete]

  get 'teams/create'

  post 'teams/create_team'

  post 'rooms/create_room'

  get 'teams/list'

  get 'teams/team'

  get 'rooms/show'

  get ":team_name/rooms/:room_name", to: 'rooms#show', as: :room

  devise_for :users
  root to: 'home#welcome'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  before_create :generate_token, unless: :token?

  belongs_to :team
  belongs_to :user

  private
  def generate_token
    self.token = SecureRandom.urlsafe_base64
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit { BroadcastMessageJob.perform_later self }
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :team
  has_many :messages

  def self.create_default_rooms(team)
      Room.create(name: "general", team: team)
  end
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  has_many :rooms
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_and_belongs_to_many :teams

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def welcome
    @own = Team.where(user: current_user)
    @teams = current_user.teams
    @invitations = Invitation.where(["email = ? and status = ?", current_user.email, false])
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def send_invitation_email
    begin
      invitation = Invitation.new(invitation_params)
      InvitationMailer.invitation_email(invitation_params[:email], invitation_params[:team_id]).deliver
      flash[:notice] = "invitation was sent successfully to: #{invitation_params[:email]}"
      invitation.user = current_user
      invitation.save
    rescue Exception => e
      flash[:alert] = e.message
    end
    redirect_to home_welcome_path
  end

  def accept
    invitation = Invitation.find_by(token: params[:token])
    current_user.teams << invitation.team
    invitation.update status: true
    redirect_to home_welcome_path
  end

  private

  def invitation_params
    params.require(:invitation).permit(:email, :team_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def show
    @chat_room = true
    begin
      @team = Team.find_by(name: params[:team_name])
      begin current_user.teams.find(@team.id)
        @room = Room.where(["name = ? and team_id = ?", params[:room_name], @team.id]).first
        @rooms = @team.rooms
        @messages = @room.messages.limit(50)
      rescue
        flash[:alert] = "You are not a member of this team"
        redirect_to root_path
      end
    rescue
      redirect_to root_path
    end
  end

  def create_room
    room = Room.create(room_params)
    redirect_to "http://#{request.host}:3000/#{room.team.name}/rooms/#{room.name}"
  end

  def room_params
    params.require(:room).permit(:name, :team_id)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!
  def create
    @team = Team.new
  end

  def create_team
    team = Team.new(team_params)
    team.user = current_user
    current_user.teams << team
    Room.create_default_rooms(team)
    team.save
    respond_to do |format|
      format.html { redirect_to root_path }
    end
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/home/welcome.html.erb
<h1>Invitations</h1>
<div class="ui container">
  <div class="divided items">
    <%= render @invitations %>
  </div>
</div>
<hr>
<h1>My Teams</h1>
<div class="ui container">
  <div class="divided items">
    <%= render @own %>
  </div>
</div>
<hr>
<h1>Joined Teams</h1>
<div class="ui container">
  <div class="divided items">
    <%= render @teams %>
  </div>
</div>

app/views/invitations/_invitation.html.erb
<h2><%= link_to invitation.team.name, url_for(controller: "invitations", action: "accept", token:invitation.token)  %></h2>

app/views/invitations/send_invitation_email.html.erb
<h1>Invitations#send_invitation_email</h1>
<p>Find me in app/views/invitations/send_invitation_email.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rslack</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <% if @chat_room %>
      <div id="new-room-modal" class="ui small modal" style="padding: 4em;">
        <h1>Create new room</h1>
        <%= form_for Room.new, url: rooms_create_room_path, html: {class: "ui form"}  do |f| %>
          <div class="field">
            <%= f.text_field :name, placeholder: "Name of room" %>
            <%= f.hidden_field :team_id, value: @team.id %>
          </div>
          <%= f.submit "submit", class: "button ui" %>
        <% end %>
      </div>
    <% end %>
    <div id="new-team-modal" class="ui small modal" style="padding: 4em;">
      <h1>Create new team</h1>
      <%= form_for Team.new, url: teams_create_team_path, html: {class: "ui form"}  do |f| %>
        <div class="field">
          <label>Name</label>
          <%= f.text_field :name, placeholder: "Name of team" %>
        </div>
        <%= f.submit "submit", class: "button ui" %>
      <% end %>
    </div>
      <div class="ui menu">
        <% if !@chat_room %>
          <div class="item borderless left">
            <a href="/"><%= image_tag 'logo.png', style: 'width:30%;'%></a>
          </div>
        <% else %>
        <div class="item">
            <h3 class="header" style="margin-left: 220px;"><%= "# #{@room.name}"%></h3>
        </div>
        <% end %>
        <% if current_user %>
        <div class="item right" style="width: 12%;">
          <div class="ui inline dropdown">
              <i class="icon ui user"></i><%= current_user.username %>
              <i class="dropdown icon"></i>
              <div class="menu inverted">
                <div class="item">
                  <%= link_to raw("<i class='ui icon power'></i>")+"Sign Out", destroy_user_session_path, method: :delete, class: "inverted" %>
                </div>
                <div class="item">
                  <%= link_to raw("<i class='ui icon tags'></i>")+"My teams", home_welcome_path %>
                </div>
                <div class="item">
                  <a id="create-team" href=""><i class='ui icon add square'></i>Create team</a>
                </div>
              </div>
          </div>
        </div>
          <% end %>
      </div>
    <div class="ui grid">
      <div class="three wide column">
        <% if @chat_room %>
          <div class="ui sidebar inverted visible vertical menu red">
            <div class="item">
              <div class="ui inline dropdown inverted">
                <div class="text">
                 <h3 style="font-weight: bold;"><%= @team.name %></h3>
                </div>
                <i class="dropdown icon"></i>
                <div class="menu inverted fluid">
                  <div class="item">
                    sjdbaH
                  </div>
                </div>
              </div>
            </div>
            <div class="item">
              <ul class="rooms_list_ul">
                <li><h2>ROOMS<span style="margin-left: 8%;"><a id="create-room" href="" style="padding-left:0.3em;padding-right:0.3em;cursor:pointer;font-weight:bold;border: 3px solid white;border-radius: 100px;">+</a></span></h2></li>
                <%= render @rooms %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
      <div class="twelve wide column">
        <% if notice %>
          <p class="ui positive message"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="ui negative message"><%= alert %></p>
        <% end %>
        <%= yield %>
      </div>
      <div class="one wide column">
      </div>
    </div>
    <script type="text/javascript" charset="utf-8">
      $(document).ready(function() {
        $('.ui.dropdown').dropdown();
        $('.ui.modal').modal();
        $("#create-room").click(function(e) {
          e.preventDefault();
          console.log("clicked");
          $('#new-room-modal').modal('show');
        });
        $("#create-team").click(function(e) {
          e.preventDefault();
          console.log("clicked");
          $('#new-team-modal').modal('show');
        });
      });
    </script>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="ui comments">
  <div class="comment">
    <a class="avatar">
      <img>
    </a>
    <div class="content">
      <a class="author"><%= message.user.username %></a>
      <div class="metadata">
        <span class="date"><%= message.created_at %></span>
      </div>
      <div class="text">
        <%= message.content %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/_room.html.erb
<li>
  <%= link_to "# #{room.name}", {action: "show", room_name: room.name, team_name: room.team.name } %>
</li>

app/views/rooms/show.html.erb
<div id="messages">
  <h1 class="header"><%= request.host %></h1>
  <%= render @messages %>
</div>
<div class="ui fluid left action input" style="padding-bottom:2%;position: fixed;bottom: 0;width: 78%;">
  <div class="ui icon button">
    <i class="plus icon"></i>
  </div>
  <input type="text" id="message_input">
</div>
<script>
  $(document).ready(function() {
  console.log("loaded...");
  var room = window.location.href.split("/").pop();
  var messages = $("#messages");
  messages.scrollTop(messages.prop('scrollHeight'));
  $("#message_input").focus();

  $("#message_input").keypress(function(e) {
  console.log($("#message_input").val());
  if(e.keyCode == 13 && $("#message_input").val()) {
  //App.room.speak($("#message_input").val(),room_name);
  App.room.speak($("#message_input").val(), room);
  $("#message_input").val("");
  }
  });
  });
</script>